name: Metadata test
on:
  push:

jobs:
  build:
    name: Determine tags to use
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAGS: ${{ toJSON( fromJSON(steps.meta.outputs.json).tags ) }}

    steps:
      - name: Determine image tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mikesir87/gha-demo
          tags: |
            type=ref,event=branch,suffix=--latest
            type=ref,event=branch,suffix=--{{sha}}
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Output config
        run: |
          echo $TAG_CONFIGURATION
        env:
          TAG_CONFIGURATION: ${{steps.meta.outputs.json}}

  record-tag:
    name: Record tag
    runs-on: ubuntu-latest
    needs: ["build"]

    steps:
      - name: Output tags
        run: |
          echo "FULL LIST: ${FULL_TAG_LIST}"
          echo "BRANCH TAG: ${BRANCH_TAG}"
        env:
          FULL_TAG_LIST: ${{ needs.build.outputs.IMAGE_TAGS }}
          BRANCH_TAG: ${{ fromJSON( needs.build.outputs.IMAGE_TAGS )[1] }}
