name: Metadata test
on:
  push:

env:
  DOCKERHUB_ORG_NAME: test-org

jobs:
  build:
    name: Determine tags to use
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAGS: ${{ toJSON( fromJSON(steps.meta.outputs.json).tags ) }}

    steps:
      - name: Set up containerd
        uses: docker/setup-docker-action@v4
        with:
          set-host: true
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Determine image tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_ORG_NAME }}/gha-demo
          tags: |
            type=ref,event=branch,suffix=--latest
            type=ref,event=branch,suffix=--{{sha}}
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Output config
        run: |
          echo $TAG_CONFIGURATION
        env:
          TAG_CONFIGURATION: ${{steps.meta.outputs.json}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          sbom: true
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  record-tag:
    name: Record tag
    runs-on: ubuntu-latest
    needs: ["build"]

    steps:
      - name: Output tags
        run: |
          echo "FULL LIST: ${FULL_TAG_LIST}"
          echo "BRANCH TAG: ${BRANCH_TAG}"
          echo "Will record to org ${DOCKERHUB_ORG_NAME}"
        env:
          FULL_TAG_LIST: ${{ needs.build.outputs.IMAGE_TAGS }}
          BRANCH_TAG: ${{ fromJSON( needs.build.outputs.IMAGE_TAGS )[1] }}
